In [3]:
import numpy as np

In [ ]:
# 1 Convert a list 1D numpy array
lst = [12.23, 13.32, 100, 36.32]
arr = np.array(lst)
print(arr)

[ 12.23  13.32 100.    36.32]


In [ ]:
# 2 3x3 matrix with values ranging from 2 to 10
arr = np.random.randint(2, 10, size = (3,3))
print(arr)

[[4 8 5]
 [5 3 2]
 [9 7 9]]


In [ ]:
# 3 create a null vector of size 10 and update sixth value to 11
arr = np.zeros(10)
arr[6] = 11
print(arr)

[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


In [ ]:
# 4 Reverse an array
lst = [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37]
arr = np.array(lst)
reverse_arr = np.flip(arr)
print(reverse_arr)

[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


In [35]:
# 5 2d array with 1 on the border and 0 inside
arr = np.zeros((5,5), dtype = 'int32')
arr[0:, 0] = 1
arr[0:, -1] = 1
arr[0, 0:] = 1
arr[-1, 0:] = 1
print(arr)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [34]:
# 6 adding border (filled with 0's) around an existing array.
arr = np.random.randint(1, 9, size = (4,7), dtype = 'int32')
rows, cols = arr.shape
border = np.zeros((1, cols), dtype = 'int32')
arr = np.vstack((border, arr, border))
border = np.zeros((rows + 2, 1), dtype = 'int32')
arr = np.hstack((border, arr, border))
print(arr)



[[0 0 0 0 0 0 0 0 0]
 [0 4 4 3 1 8 1 2 0]
 [0 7 1 4 4 7 3 5 0]
 [0 2 5 6 1 3 5 6 0]
 [0 8 4 5 2 1 2 5 0]
 [0 0 0 0 0 0 0 0 0]]


In [8]:
# 7 Checkerboard pattern
checker_board = np.zeros((8, 8), dtype='int32')
checker_board[0::2, 1::2] = 1
checker_board[1::2, 0::2] = 1
print(checker_board)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [40]:
# 8 List to array
lst = [1, 2, 3, 4, 5, 6, 7, 8]
arr = np.array(lst)
arr = arr.reshape((4,2))
print(arr)

# tuple to array
tup = ([[8, 4, 6],
        [1, 2, 3]])
arr = np.array(tup)
print(arr)


[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[8 4 6]
 [1 2 3]]


In [30]:
# 9 Append values to the end of an array
arr = np.array([10, 20, 30])
arr = np.concatenate((arr,[40, 50, 60, 70, 80, 90]))
print(arr)

[10 20 30 40 50 60 70 80 90]


In [41]:
# 10 Print real and imaginary part from complex numbers
arr = np.array([ 1.00000000+0.j, 0.70710678+0.70710678j])
real = arr.real
imaginary = arr.imag
print(f"Real part of the array : \n {real}")
print(f"Imaginary part of the array : \n {imaginary}")

Real part of the array : 
 [1.         0.70710678]
Imaginary part of the array : 
 [0.         0.70710678]


In [45]:
# 11 Number of elements, Length of element, Total bytes consumed by the elements
arr = np.arange(1, 100, 2)
print(f"Size of the array: {arr.size}")
print(f"Length of one array element in bytes: {arr.itemsize}")
print(f"Total bytes consumed by the elements of the array: {arr.size * arr.itemsize}")

Size of the array: 50
Length of one array element in bytes: 8
Total bytes consumed by the elements of the array: 400


In [ ]:
# 12 Common values in two array
arr1 = np.array([0, 10, 20, 40, 60])
arr2 = np.array([10, 30, 40])
result = np.intersect1d(arr1, arr2, assume_unique=True)
print(result)

[10 40]


In [ ]:
# 13 Set difference of two array
arr1 = np.array([0, 10, 20, 40, 60, 80])
arr2 = np.array([10, 30, 40, 50, 70, 90])
result = np.setdiff1d(arr1, arr2, assume_unique=True)
print(result)


[ 0 20 60 80]


In [5]:
# 14 Set Exclusive or of two arrays
arr1 = np.array([0, 10, 20, 40, 60, 80])
arr2 = np.array([10, 30, 40, 50, 70])
result = np.setxor1d(arr1, arr2, assume_unique=True)
print(result)


[ 0 20 30 50 60 70 80]


In [9]:
# 15 Compare two arrays using numpy
arr1 = np.array([1, 2])
arr2 = np.array([4, 5])
result = arr1 > arr2
print(result)
result = arr1 >= arr2
print(result)
result = arr1 < arr2
print(result)
result = arr1 <= arr2
print(result)

[False False]
[False False]
[ True  True]
[ True  True]
