In [143]:
import numpy as np

In [144]:
# 1 Convert a list 1D numpy array
lst = [12.23, 13.32, 100, 36.32]
arr = np.array(lst)
print(arr)

[ 12.23  13.32 100.    36.32]


In [145]:
# 2 3x3 matrix with values ranging from 2 to 10
arr = np.random.randint(2, 10, size = (3,3))
print(arr)

[[8 6 6]
 [9 3 3]
 [8 4 6]]


In [146]:
# 3 create a null vector of size 10 and update sixth value to 11
arr = np.zeros(10)
arr[6] = 11
print(arr)

[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


In [147]:
# 4 Reverse an array
lst = [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37]
arr = np.array(lst)
reverse_arr = np.flip(arr)
print(reverse_arr)

[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


In [148]:
# 5 2d array with 1 on the border and 0 inside
arr = np.zeros((5,5), dtype = 'int32')
arr[0:, 0] = 1
arr[0:, -1] = 1
arr[0, 0:] = 1
arr[-1, 0:] = 1
print(arr)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [149]:
# 6 adding border (filled with 0's) around an existing array.
arr = np.random.randint(1, 9, size = (4,7), dtype = 'int32')
rows, cols = arr.shape
border = np.zeros((1, cols), dtype = 'int32')
arr = np.vstack((border, arr, border))
border = np.zeros((rows + 2, 1), dtype = 'int32')
arr = np.hstack((border, arr, border))
print(arr)



[[0 0 0 0 0 0 0 0 0]
 [0 8 1 3 4 2 3 3 0]
 [0 8 8 2 7 4 4 5 0]
 [0 2 4 5 5 4 5 4 0]
 [0 1 8 4 7 5 2 3 0]
 [0 0 0 0 0 0 0 0 0]]


In [150]:
# 7 Checkerboard pattern
checker_board = np.zeros((8, 8), dtype='int32')
checker_board[0::2, 1::2] = 1
checker_board[1::2, 0::2] = 1
print(checker_board)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [151]:
# 8 List to array
lst = [1, 2, 3, 4, 5, 6, 7, 8]
arr = np.array(lst)
arr = arr.reshape((4,2))
print(arr)

# tuple to array
tup = ([[8, 4, 6],
        [1, 2, 3]])
arr = np.array(tup)
print(arr)


[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[8 4 6]
 [1 2 3]]


In [152]:
# 9 Append values to the end of an array
arr = np.array([10, 20, 30])
arr = np.concatenate((arr,[40, 50, 60, 70, 80, 90]))
print(arr)

[10 20 30 40 50 60 70 80 90]


In [153]:
# 10 Print real and imaginary part from complex numbers
arr = np.array([ 1.00000000+0.j, 0.70710678+0.70710678j])
real = arr.real
imaginary = arr.imag
print(f"Real part of the array : \n {real}")
print(f"Imaginary part of the array : \n {imaginary}")

Real part of the array : 
 [1.    0.707]
Imaginary part of the array : 
 [0.    0.707]


In [154]:
# 11 Number of elements, Length of element, Total bytes consumed by the elements
arr = np.arange(1, 100, 2)
print(f"Size of the array: {arr.size}")
print(f"Length of one array element in bytes: {arr.itemsize}")
print(f"Total bytes consumed by the elements of the array: {arr.size * arr.itemsize}")

Size of the array: 50
Length of one array element in bytes: 8
Total bytes consumed by the elements of the array: 400


In [155]:
# 12 Common values in two array
arr1 = np.array([0, 10, 20, 40, 60])
arr2 = np.array([10, 30, 40])
result = np.intersect1d(arr1, arr2, assume_unique=True)
print(result)

[10 40]


In [156]:
# 13 Set difference of two array
arr1 = np.array([0, 10, 20, 40, 60, 80])
arr2 = np.array([10, 30, 40, 50, 70, 90])
result = np.setdiff1d(arr1, arr2, assume_unique=True)
print(result)


[ 0 20 60 80]


In [157]:
# 14 Set Exclusive or of two arrays
arr1 = np.array([0, 10, 20, 40, 60, 80])
arr2 = np.array([10, 30, 40, 50, 70])
result = np.setxor1d(arr1, arr2, assume_unique=True)
print(result)


[ 0 20 30 50 60 70 80]


In [158]:
# 15 Compare two arrays using numpy
arr1 = np.array([1, 2])
arr2 = np.array([4, 5])
result = arr1 > arr2
print(result)
result = arr1 >= arr2
print(result)
result = arr1 < arr2
print(result)
result = arr1 <= arr2
print(result)

[False False]
[False False]
[ True  True]
[ True  True]


In [159]:
# 16 flattened array
arr = np.array([[10, 20, 30],
        [20, 40, 50]])
arr = arr.flatten()
print(arr)

[10 20 30 20 40 50]


In [160]:
# 17 Change the data type of an array
arr = np.array([[2, 4, 6],
                [6, 8, 10]])
print(f"Data type of the array x is: {arr.dtype}")
arr = np.astype(arr, 'float64')
print(f"New type: {arr.dtype}")

Data type of the array x is: int64
New type: float64


In [161]:
# 18 2D array with diagonal ones and rest zeros
arr = np.zeros((6,6))
rows, cols = arr.shape
min = rows if rows < cols else cols
for i in range(min):
    arr[i, i] = 1
    
print(arr)
# builtin function
arr = np.fill_diagonal(arr, 1)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [162]:
# 19 diagonal and upper diagonal elements are 0 and below diagonal elements are 1
arr = np.random.randint(1, 9, (10, 8))
rows, cols = arr.shape
for i in range(rows):
    arr[i, :i] = 1
print(arr)

# Built in function
arr = np.tril(arr, k = -1)

[[4 3 7 6 4 5 6 5]
 [1 3 7 5 8 3 6 6]
 [1 1 2 7 8 3 1 8]
 [1 1 1 2 7 7 8 3]
 [1 1 1 1 1 4 8 2]
 [1 1 1 1 1 8 5 7]
 [1 1 1 1 1 1 8 1]
 [1 1 1 1 1 1 1 8]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]]


In [163]:
# 20 Concate 2D two arrays
arr1 = np.array([[0, 1, 3], [5, 7, 9]])
arr2 = np.array([[0, 2, 4], [6, 8, 10]])
arr = np.concatenate((arr1, arr2), axis=1)
print(arr)

[[ 0  1  3  0  2  4]
 [ 5  7  9  6  8 10]]


In [164]:
# 21 Immutable array
arr = np.arange(1, 9,  8)
arr.setflags(write=False)
arr[1] = 1

ValueError: assignment destination is read-only

In [ ]:
# 22 Multiply every element in 2D array with 3
arr = np.array([[0, 1, 2, 3],
            [4, 5, 6, 7],
        [8, 9, 10, 11]])
arr = arr * 3
print(arr)

[[ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]]


In [ ]:
# 23 Convert ndarray into list
arr = np.array([[0, 1],
            [2, 3],
            [4, 5]])
lst = arr.tolist()
print(lst)

[[0, 1], [2, 3], [4, 5]]


In [ ]:
# 24 Convert ndarray into list
arr = np.array([0.26153123, 0.52760141, 0.5718299, 0.5927067, 0.7831874, 0.69746349,
        0.35399976, 0.99469633, 0.0694458, 0.54711478])
# set print precesion to 3
np.set_printoptions(precision=3)
lst = np.round(arr, 3).tolist()
print(arr)
print(lst)

[0.262 0.528 0.572 0.593 0.783 0.697 0.354 0.995 0.069 0.547]
[0.262, 0.528, 0.572, 0.593, 0.783, 0.697, 0.354, 0.995, 0.069, 0.547]


In [ ]:
# 25 Print array values with precesion 3
arr = np.array([1.60000000e-10, 1.60000000e+00, 1.20000000e+03, 2.35000000e-01])
np.set_printoptions(suppress=True, precision=3)
print(arr)


[   0.       1.6   1200.       0.235]


In [ ]:
# 26 Adding an extra column to numpy array
arr = np.array([[10, 20, 30],
            [40, 50, 60]])
extra = np.array([[100],[200]])
arr = np.hstack((arr, extra))
print(arr)

[[ 10  20  30 100]
 [ 40  50  60 200]]


In [ ]:
# 27 Remove specified element from numpy array
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
arr = np.delete(arr, [0, 3, 4])
print(arr)

[ 20  30  60  70  80  90 100]


In [ ]:
# File I/O operation
arr = np.array([[10, 20, 30, 40, 50, 60, 70, 80, 90, 100], 
                [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]], dtype='int32')
np.savetxt('array.txt', arr, fmt="%d")
arr = np.loadtxt('array.txt')
print(arr)

[[ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]
 [ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]]
