In [1]:
import numpy as np

In [3]:
#Reshape to (3, 4)
arr = np.arange(12)
reshape_arr = arr.reshape(3, 4)
reshape_arr[0][0] = 99
print(arr[0] == reshape_arr[0][0])

True


In [6]:
# Create a view using reshape
# Create a copy using .copy()

arr = np.array([10, 20, 30, 40])
reshape = arr.reshape(2, 2)
copy = arr.copy()
reshape[0][0] = 12
print(reshape[0][0] == arr[0])
copy[0] = 15
print(copy[0] == arr[0])

True
False


In [9]:
# Use ravel()
# Use flatten()

matrix = np.array([[1, 2], [3, 4]])
ravel = matrix.ravel()
flatten = matrix.flatten()
ravel[0] = 10
print(matrix[0][0] == ravel[0])
flatten[0] = 14
print(matrix[0][0] == flatten[0])

True
False


In [11]:
# Change shape using .shape
# Try an invalid shape and observe error

arr = np.arange(8)
arr.shape = (2, 2, 2)

# Invalid shape
arr.shape = (3, 3)

ValueError: cannot reshape array of size 8 into shape (3,3)

In [12]:
# Check memory between:
# Original & reshaped array
# Original & copied array

arr = np.arange(8)
reshape = arr.reshape(2, 4)
print(reshape)
copy = arr.copy()
print(np.shares_memory(arr, reshape))
print(np.shares_memory(arr, copy))

[[0 1 2 3]
 [4 5 6 7]]
True
False


In [14]:
# Axis and concatenate
# Sum along axis=0
# Sum along axis=1

arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print(arr.sum(axis=0))
print(arr.sum(axis=1))

[5 7 9]
[ 6 15]


In [25]:
# Stack them vertically

a = np.array([10, 20, 30])
b = np.array([40, 50, 60])

c2 = np.vstack((a, b))
print(c2)

[[10 20 30]
 [40 50 60]]


In [27]:
# Stack them horizontally

a = np.array([[1, 2],
              [3, 4]])
b = np.array([[5, 6],
              [7, 8]])
c = np.hstack((a, b))
c

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [28]:
# Concatenate along axis=0
# Concatenate along axis=1

a = np.array([[1, 2],
              [3, 4]])
b = np.array([[5, 6],
              [7, 8]])
c1 = np.concatenate((a, b), axis=0)
print(c1)
c2 = np.concatenate((a, b), axis=1)
print(c2)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [29]:
# Split into 4 equal parts.

arr = np.arange(12)
np.split(arr, 4)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8]), array([ 9, 10, 11])]

In [31]:
# Split horizontally into 2 parts
# Split vertically into 4 parts

matrix = np.arange(16).reshape(4, 4)
print(np.split(matrix, 2, axis=1))
print(np.split(matrix, 4, axis=0))

[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]]), array([[12, 13, 14, 15]])]


In [36]:
# Extract values greater than 10
# Extract values between 10 and 30

arr = np.array([12, 5, 30, 7, 25])
print(arr[arr > 10])
print(arr[(arr >= 10) & (arr <= 30)])

[12 30 25]
[12 30 25]


In [40]:
# Replace all negative values with 0.

arr = np.array([5, -2, 10, -7, 15])
arr[ arr < 0 ] = 0
arr

array([ 5,  0, 10,  0, 15])

In [41]:
# marks ≥ 40 AND ≤ 70

marks = np.array([35, 60, 80, 40, 25])
print(marks[(marks >= 40) & (marks <= 70)])

[60 40]


In [46]:
# Select students who passed (marks ≥ 40)
# Select students who failed (marks < 40)

students = np.array([
    [1, 45],
    [2, 32],
    [3, 78],
    [4, 50]
])

print(f"Passed students \n{students[students[:, 1] >= 40, 0]}")
print(f"Failed students \n{students[students[:, 1] < 40, 0]}")



Passed students 
[1 3 4]
Failed students 
[2]


In [47]:
# Check if any temperature > 38
# Check if all temperatures ≥ 30

temps = np.array([32, 35, 30, 28, 40])

print(np.any(temps > 38))
print(np.all(temps >= 30))

True
False


In [51]:
# Sort without modifying original
# Sort modifying original

arr = np.array([45, 10, 30, 25])

# sort without modifying original
print(np.sort(arr))

# Sort modifying original
arr.sort()
arr

[10 25 30 45]


array([10, 25, 30, 45])

In [ ]:
# Sort row-wise
# Sort column-wise

matrix = np.array([
    [3, 1, 2],
    [6, 4, 5]
])

print(f"row wise sort \n {np.sort(matrix, axis=1)}")
print(f"colomn wise sort \n {np.sort(matrix, axis=0)}")


row wise sort 
 [[1 2 3]
 [4 5 6]]
colomn wise sort 
 [[3 1 2]
 [6 4 5]]


In [53]:
# Get indices that would sort scores in ascending order.

scores = np.array([88, 92, 79, 95])
print(np.argsort(scores))

[2 0 1 3]


In [55]:
# Mean
# Median
# Standard deviation

data = np.array([10, 20, 30, 40, 50])
print(data.mean())
print(np.median(data))
print(data.std())

30.0
30.0
14.142135623730951


In [ ]:
# Find indices where value is 15
# Find indices where value > 20

arr = np.array([5, 15, 25, 35, 15])
print(np.where(arr == 15))
print(np.where(arr > 20))

# Normalizing cost data using log transformation
hospital_df['normalized_cost'] = np.log1p(hospital_df['treatment_cost'])
print("Normalized treatment costs:")
print(hospital_df[['treatment_cost', 'normalized_cost']].head())   

(array([1, 4]),)
(array([2, 3]),)
