[[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]]

perform : 
* Find row-wise sum
* Find column-wise mean
* Replace values > 5 with 0
* Extract elements divisible by 2
* Flatten using ravel()

In [10]:
import numpy as np

In [11]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

In [12]:
# Find row-wise sum
print(np.sum(arr, axis=1))

[ 6 15 24]


In [13]:
# Find column-wise mean
print(np.mean(arr, axis=0))

[4. 5. 6.]


In [17]:
# Replace values > 5 with 0
new_arr = np.where(arr > 5, 0, arr)
print(new_arr)

[[1 2 3]
 [4 5 0]
 [0 0 0]]


In [15]:
# Extract elements divisible by 2
div_elements = arr[arr%2 == 0]
print(div_elements)

[2 4 6 8]


In [18]:
# Flatten using ravel()
flat = arr.ravel()
print(flat)

[1 2 3 4 5 6 7 8 9]
