<!-- Create this array:
[2, 4, 6, 8, 10]

Then:

Multiply all elements by 3
Replace elements greater than 15 with -1
Print indices of elements equal to -1
Use np.where() to create a new array:
if value > 5 → 1
else → 0 -->

In [2]:
import numpy as np

In [3]:
arr = np.array([2, 4, 6, 8, 10])

# Multiply all elements by 3
mul_arr = arr * 3
print(mul_arr)

[ 6 12 18 24 30]


In [4]:
# Replace elements greater than 15 with -1
mul_arr[mul_arr > 15] = -1
print(mul_arr)

[ 6 12 -1 -1 -1]


In [5]:
# Print indices of elements equal to -1
print(np.argwhere(mul_arr == -1))

[[2]
 [3]
 [4]]


In [7]:
# Use np.where() to create a new array:
# if value > 5 → 1
# else → 0

new_arr = np.where(arr > 5, 1, 0)
print(new_arr)

[0 0 1 1 1]
