[[1, 2, np.nan],
 [4, np.nan, 6],
 [7, 8, 9]]

Perform:
Replace NaN with column-wise mean
Find row with maximum sum
Normalize array (0 to 1 scale):
(𝑥−𝑚𝑖𝑛)/(𝑚𝑎𝑥−𝑚𝑖𝑛)
Find indices where values > 0.5 after normalization
Flatten and remove duplicates

In [29]:
import numpy as np

In [30]:
arr = np.array([[1, 2, np.nan],
                [4, np.nan, 6],
                [7, 8, 9]])

In [31]:
# Replace NaN with column-wise mean
col_mean = np.nanmean(arr, axis=0)
print(col_mean)
inds = np.where(np.isnan(arr))
print(inds)
arr[inds] = np.take(col_mean, inds[1])
print(arr)

[4.  5.  7.5]
(array([0, 1]), array([2, 1]))
[[1.  2.  7.5]
 [4.  5.  6. ]
 [7.  8.  9. ]]


In [32]:
# Find row with maximum sum
max_sum = np.sum(arr, axis=1)
print(np.argmax(max_sum))

2


In [33]:
# Normalize array (0 to 1 scale): (𝑥−𝑚𝑖𝑛)/(𝑚𝑎𝑥−𝑚𝑖𝑛)
nrm_arr = (arr - np.min(arr)) / (np.max(arr) - np.min(arr))
print(nrm_arr)

[[0.     0.125  0.8125]
 [0.375  0.5    0.625 ]
 [0.75   0.875  1.    ]]


In [34]:
# Find indices where values > 0.5 after normalization
max_ind = np.argwhere(nrm_arr > 0.5)
print(max_ind)

[[0 2]
 [1 2]
 [2 0]
 [2 1]
 [2 2]]


In [35]:
# Flatten and remove duplicates
flat = nrm_arr.flatten()
uq = np.unique(nrm_arr)
print(uq)

[0.     0.125  0.375  0.5    0.625  0.75   0.8125 0.875  1.    ]
